[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
user=root
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:flask]
command=/opt/okta-agent-api/venv/bin/python /opt/okta-agent-api/app.py
directory=/opt/okta-agent-api
autostart=true
autorestart=true
user=www-data
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
